### ISSUE TITLE
Design feedback: Global fonts and hero/banner section

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#159]
Had a design review session with @tiyiprh and got some feedback.

```[tasklist]
### Tasks
- [x] Use Red Hat display as the font family on all text
- [x] Use regular and medium instead of bold font weight on the banner band. Lower the font weight to match the wireframe.
- [x] On the banner band, increase width of text in the last column of the row so that the "Ansible version" and command text doesn't get squashed down.
- [x] Add hover text to the "pip install ansible" button to make it clear that the text is copied.
- [x] Add right arrow to the platform "learn more" button on the banner.
- [x] Change arrow in circle on learn more links to right arrow that matches the back to top arrow.
```
