### ISSUE TITLE
Design feedback: Update icon colours and community section

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#160]
More review feedback from @tiyiprh on icon colours and changes to the community section.

```[tasklist]
### Tasks
- [x] Use cyan for icons in each section and the menu bar
- [x] Use cyan for the community icons
- [x] Add text for each icon in the community section
- [x] Add hover for each icon in the community section - possibly update so added text gets hover
- [x] Change button color on bullhorn band - subscribe should be cyan
```
