### ISSUE TITLE
Design feedback: Bullhorn band, Contribute links, Events

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#161]
```[tasklist]
### Tasks
- [ ] Increase the width of the subscribe input field or center it under the text
- [ ] Move bullhorn band between community and blogs
- [ ] Contribute section - put learn more link inline with the text - underline the link text in the body
- [ ] Add back to top to the events section
```
