### ISSUE TITLE
Blog post migration: Cleaning up image references

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#353]
This issue follows up on #300

Several migrated blog posts contain references to hosted images on HubSpot (ansible.com) or Google user content. There is manual effort required for image references within the converted markdown files.

```[tasklist]
### Tasks
- [x] Remove as many image references as possible: https://github.com/ansible-community/community-website/issues/353#issuecomment-1876962088
- [x] Download all required images and add them to the source repository: https://github.com/ansible-community/community-website/issues/353#issuecomment-1878459587
- [x] Remove all unnecessary HTML and inline CSS from image references: https://github.com/ansible-community/community-website/issues/353#issuecomment-1876929242
- [x] Ensure all image references are in valid markdown format and add alternative text to image references where needed: https://github.com/ansible-community/community-website/issues/353#issuecomment-1876972412
```

**Comment by oraNod** [comment]
To remove all the unnecessary HTML and inline CSS bits from the conversion you can do something like this:

## Before

```
![NRE 1](https://www.ansible.com/hs-fs/hubfs/NRE%201.png?width=986&name=NRE%201.png){width="986"
style="width: 986px;"
srcset="https://www.ansible.com/hs-fs/hubfs/NRE%201.png?width=493&name=NRE%201.png 493w, https://www.ansible.com/hs-fs/hubfs/NRE%201.png?width=986&name=NRE%201.png 986w, https://www.ansible.com/hs-fs/hubfs/NRE%201.png?width=1479&name=NRE%201.png 1479w, https://www.ansible.com/hs-fs/hubfs/NRE%201.png?width=1972&name=NRE%201.png 1972w, https://www.ansible.com/hs-fs/hubfs/NRE%201.png?width=2465&name=NRE%201.png 2465w, https://www.ansible.com/hs-fs/hubfs/NRE%201.png?width=2958&name=NRE%201.png 2958w"
sizes="(max-width: 986px) 100vw, 986px"}
```

Here you can see the conversion created an image reference in markdown format: `![text](url)` but it also includes a bunch of HTML attributes and CSS properties that are not necessary. We can simply delete all that.

## After

```
![NRE 1](https://www.ansible.com/hs-fs/hubfs/NRE%201.png)
```

**Comment by oraNod** [comment]
# Removing decorative image references

A number of the image references are for decorative purposes and do not convey meaning to users. In the interest of accessibility and simplicity we should remove these image references altogether.

Here is an example in the `large-scale-deployments-using-ansible.md` file: https://www.ansible.com/hs-fs/hubfs/2018_Images/Social-Blog/Ansible-Tower-Large-Scale-Deployment.png

While this image might provide some aesthetic qualities to the post it does not supplement or accompany the text in a way that helps users understand the content. Rather than keeping these sort of images during the clean up effort it would be better to remove them for accessibility, longer term maintenance, and overall performance.

Here are some more examples of image references that could be considered more decorative than informative:

https://www.ansible.com/hs-fs/hubfs/2018_Images/Social-Blog/Ansible-Simple-Powerful-Agentless.png

https://www.ansible.com/hs-fs/hubfs/Images/blog-social/blog_ansible-and-service-now-part2.png

https://www.ansible.com/hs-fs/hubfs/Images/blog-social/blog_getting-started_content-collections.png

**Comment by oraNod** [comment]
# Checking markdown format and adding alternative text to images

We should ensure all image references have alternative text. As a best effort we should ensure that the alternative text is meaningful.

Here is an example in the `getting-started-with-ansible-collections.md` file:

```
![Screen Shot 2019-11-13 at 4.11.45
PM](https://www.ansible.com/hs-fs/hubfs/Screen%20Shot%202019-11-13%20at%204.11.45%20PM.png)
```

There are two issues with this reference:

1. The image reference is on multiple lines.
2. The alternative text is confusing and not very meaningful.

An improvement could be as follows:

```
![Collection directory layout](https://www.ansible.com/hs-fs/hubfs/Screen%20Shot%202019-11-13%20at%204.11.45%20PM.png)
```

**Comment by oraNod** [comment]
# Downloading images and adding to source

**Downloading and copying images takes up space and will increase the size of the repository and resulting container image so use caution when adding images to source.**
