### ISSUE TITLE
Add media queries and breakpoints for responsiveness

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#47]
Media queries and breakpoints will ensure that the site looks nice and behaves as expected on all devices, including mobile displays.

Content on the homepage should be "stacked" in each section as per the wireframe. Additionally we might choose to hide "no display" certain elements like the clipboard button on mobile (nobody is going to pip install ansible in a terminal on their phone).

```[tasklist]
### Tasks
- [x] Homepage banner including navbar
- [x] Tabbed menu bar
- [x] Automate section (Why Ansible)
- [x] Ecosystem
- [x] Community
- [x] Blog
- [x] Contribute
- [x] Subscribe to the Bullhorn
- [x] Events
- [x] Platform
- [x] Footer
```

**Comment by tiyiprh** [comment]
Can take this one as well
